// calm-studio/apps/studio/src/lib/palette/NodePalette.svelte
<!-- SPDX-FileCopyrightText: 2024 CalmStudio contributors - see NOTICE file -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script lang="ts">
	import { useDnD } from './DnDProvider.svelte';
	import { getAllPacks, initAllPacks } from '@calmstudio/extensions';
	import type { PackDefinition, NodeTypeEntry } from '@calmstudio/extensions';

	// Register all packs on import so they're available immediately
	initAllPacks();

	const dnd = useDnD();

	let { onplacenode }: { onplacenode?: (type: string) => void } = $props();

	let searchQuery = $state('');
	let showCustomInput = $state(false);
	let customTypeValue = $state('');

	// Track expand/collapse state per pack id. Core starts expanded; others collapsed.
	let expandedSections = $state<Record<string, boolean>>({ core: true });

	const allPacks = $derived(getAllPacks());

	/** Flat list of all nodes across all packs for search */
	interface SearchResult {
		node: NodeTypeEntry;
		pack: PackDefinition;
	}

	const searchResults = $derived((): SearchResult[] => {
		if (searchQuery.trim() === '') return [];
		const query = searchQuery.toLowerCase();
		const results: SearchResult[] = [];
		for (const pack of allPacks) {
			for (const node of pack.nodes) {
				if (
					node.label.toLowerCase().includes(query) ||
					node.typeId.toLowerCase().includes(query)
				) {
					results.push({ node, pack });
				}
			}
		}
		return results;
	});

	const isSearching = $derived(searchQuery.trim() !== '');

	function toggleSection(packId: string) {
		expandedSections = {
			...expandedSections,
			[packId]: !expandedSections[packId],
		};
	}

	function isSectionExpanded(packId: string): boolean {
		return expandedSections[packId] ?? false;
	}

	function handleDragStart(event: DragEvent, typeId: string) {
		if (!event.dataTransfer) return;
		event.dataTransfer.setData('application/calm-node-type', typeId);
		event.dataTransfer.effectAllowed = 'copy';
		dnd.setDragType(typeId);
	}

	function handleDragEnd() {
		dnd.setDragType(null);
	}

	function handleClick(typeId: string) {
		onplacenode?.(typeId);
	}

	function handleCustomKeydown(event: KeyboardEvent) {
		if (event.key === 'Enter') {
			const trimmed = customTypeValue.trim();
			if (trimmed) {
				onplacenode?.(trimmed);
				customTypeValue = '';
				showCustomInput = false;
			}
		} else if (event.key === 'Escape') {
			showCustomInput = false;
			customTypeValue = '';
		}
	}
</script>

<aside class="palette" aria-label="CALM node palette">
	<!-- Header -->
	<div class="palette-header">
		<svg class="header-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
			<rect x="3" y="3" width="7" height="7" rx="1.5"/>
			<rect x="14" y="3" width="7" height="7" rx="1.5"/>
			<rect x="3" y="14" width="7" height="7" rx="1.5"/>
			<rect x="14" y="14" width="7" height="7" rx="1.5"/>
		</svg>
		<span class="header-label">Components</span>
	</div>

	<!-- Search -->
	<div class="search-wrapper">
		<div class="search-container">
			<svg class="search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
				<circle cx="11" cy="11" r="8" />
				<path d="m21 21-4.35-4.35" />
			</svg>
			<input
				type="search"
				placeholder="Search all packs..."
				bind:value={searchQuery}
				class="search-input"
				aria-label="Search node types"
			/>
		</div>
	</div>

	<!-- Main content: search results OR collapsible sections -->
	<div class="palette-body">
		{#if isSearching}
			<!-- Search results: flat list with pack badge attribution -->
			<ul class="palette-list" role="list" aria-label="Search results">
				{#each searchResults() as { node, pack } (node.typeId)}
					<li>
						<button
							type="button"
							draggable="true"
							ondragstart={(e) => handleDragStart(e, node.typeId)}
							ondragend={handleDragEnd}
							ondblclick={() => handleClick(node.typeId)}
							class="palette-item"
							aria-label="Drag or double-click to place {node.label} node"
							title={node.description ?? node.label}
						>
							<span class="item-icon" style="background: {node.color.border}20; color: {node.color.stroke};">
								{@html node.icon}
							</span>
							<span class="item-label">{node.label}</span>
							{#if pack.color.badge}
								<span class="pack-badge" style="color: {pack.color.stroke}; border-color: {pack.color.border}40;">
									{pack.color.badge}
								</span>
							{/if}
						</button>
					</li>
				{/each}

				{#if searchResults().length === 0}
					<li class="empty-state">
						No match for "{searchQuery}"
					</li>
				{/if}
			</ul>
		{:else}
			<!-- Collapsible pack sections -->
			{#each allPacks as pack (pack.id)}
				<div class="pack-section">
					<!-- Section header -->
					<button
						type="button"
						class="section-header"
						class:expanded={isSectionExpanded(pack.id)}
						onclick={() => toggleSection(pack.id)}
						aria-expanded={isSectionExpanded(pack.id)}
						aria-label="Toggle {pack.label} section"
						style="--pack-color: {pack.color.border};"
					>
						<svg
							class="chevron"
							class:rotated={isSectionExpanded(pack.id)}
							viewBox="0 0 16 16"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							aria-hidden="true"
						>
							<path d="M4 6l4 4 4-4" stroke-linecap="round" stroke-linejoin="round"/>
						</svg>
						<span class="section-label">{pack.label}</span>
						<span class="section-count">{pack.nodes.length}</span>
					</button>

					<!-- Section body -->
					{#if isSectionExpanded(pack.id)}
						<ul class="palette-list section-body" role="list" aria-label="{pack.label} nodes">
							{#each pack.nodes as node (node.typeId)}
								<li>
									<button
										type="button"
										draggable="true"
										ondragstart={(e) => handleDragStart(e, node.typeId)}
										ondragend={handleDragEnd}
										ondblclick={() => handleClick(node.typeId)}
										class="palette-item"
										aria-label="Drag or double-click to place {node.label} node"
										title={node.description ?? node.label}
									>
										<span class="item-icon" style="background: {node.color.border}20; color: {node.color.stroke};">
											{@html node.icon}
										</span>
										<span class="item-label">{node.label}</span>
									</button>
								</li>
							{/each}
						</ul>
					{/if}
				</div>
			{/each}
		{/if}
	</div>

	<!-- Custom node entry (always at bottom) -->
	<div class="palette-footer">
		{#if showCustomInput}
			<input
				type="text"
				placeholder="Enter type name..."
				bind:value={customTypeValue}
				onkeydown={handleCustomKeydown}
				class="custom-input"
				aria-label="Custom node type input"
				autofocus
			/>
			<p class="custom-hint">
				Enter to place &middot; Esc to cancel
			</p>
		{:else}
			<button
				type="button"
				onclick={() => (showCustomInput = true)}
				class="custom-btn"
				aria-label="Create a custom node type"
			>
				<span class="custom-icon">
					<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
						<line x1="12" y1="5" x2="12" y2="19" />
						<line x1="5" y1="12" x2="19" y2="12" />
					</svg>
				</span>
				<span class="item-label">Custom...</span>
			</button>
		{/if}
	</div>
</aside>

<style>
	.palette {
		display: flex;
		flex-direction: column;
		width: 100%;
		max-width: 280px;
		height: 100%;
		flex-shrink: 0;
		background: var(--color-surface);
		border-right: 1px solid var(--color-border);
		font-family: var(--font-sans);
	}

	:global(.dark) .palette {
		background: #0f1320;
		border-color: #1e293b;
	}

	/* Header */
	.palette-header {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 14px 16px;
		border-bottom: 1px solid var(--color-border);
		flex-shrink: 0;
	}

	:global(.dark) .palette-header {
		border-color: #1e293b;
	}

	.header-icon {
		width: 15px;
		height: 15px;
		color: var(--color-accent);
	}

	:global(.dark) .header-icon {
		color: #818cf8;
	}

	.header-label {
		font-size: 11px;
		font-weight: 700;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--color-text-tertiary);
	}

	:global(.dark) .header-label {
		color: #64748b;
	}

	/* Search */
	.search-wrapper {
		padding: 10px 12px;
		flex-shrink: 0;
	}

	.search-container {
		position: relative;
	}

	.search-icon {
		position: absolute;
		left: 10px;
		top: 50%;
		transform: translateY(-50%);
		width: 14px;
		height: 14px;
		color: var(--color-text-tertiary);
		pointer-events: none;
	}

	.search-input {
		width: 100%;
		padding: 7px 12px 7px 32px;
		font-size: 12px;
		font-family: inherit;
		color: var(--color-text-primary);
		background: var(--color-surface-secondary);
		border: 1px solid var(--color-border);
		border-radius: 8px;
		outline: none;
		transition: all 0.15s ease;
		box-sizing: border-box;
	}

	.search-input::placeholder {
		color: var(--color-text-tertiary);
	}

	.search-input:focus {
		border-color: var(--color-accent);
		box-shadow: 0 0 0 2px rgba(99, 102, 241, 0.12);
	}

	:global(.dark) .search-input {
		background: #1e293b;
		border-color: #334155;
		color: #e2e8f0;
	}

	:global(.dark) .search-input::placeholder {
		color: #64748b;
	}

	:global(.dark) .search-input:focus {
		border-color: #818cf8;
		box-shadow: 0 0 0 2px rgba(129, 140, 248, 0.15);
	}

	/* Scrollable body */
	.palette-body {
		flex: 1;
		overflow-y: auto;
	}

	/* Palette list */
	.palette-list {
		padding: 4px 8px;
		margin: 0;
		list-style: none;
	}

	.section-body {
		padding-top: 2px;
		padding-bottom: 4px;
	}

	.palette-item {
		display: flex;
		width: 100%;
		align-items: center;
		gap: 10px;
		padding: 7px 10px;
		border: none;
		background: transparent;
		border-radius: 8px;
		cursor: grab;
		text-align: left;
		font-family: inherit;
		transition: all 0.15s ease;
	}

	.palette-item:hover {
		background: var(--color-surface-tertiary);
	}

	.palette-item:active {
		cursor: grabbing;
	}

	:global(.dark) .palette-item:hover {
		background: #1e293b;
	}

	.item-icon {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 30px;
		height: 30px;
		border-radius: 7px;
		flex-shrink: 0;
		transition: all 0.15s ease;
	}

	:global(.dark) .item-icon {
		background: rgba(255, 255, 255, 0.06) !important;
	}

	.item-label {
		font-size: 12.5px;
		font-weight: 500;
		color: var(--color-text-secondary);
		transition: color 0.15s ease;
		flex: 1;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.palette-item:hover .item-label {
		color: var(--color-text-primary);
	}

	:global(.dark) .item-label {
		color: #94a3b8;
	}

	:global(.dark) .palette-item:hover .item-label {
		color: #e2e8f0;
	}

	/* Pack badge in search results */
	.pack-badge {
		font-size: 9px;
		font-weight: 600;
		padding: 1px 4px;
		border-radius: 3px;
		border: 1px solid;
		flex-shrink: 0;
		white-space: nowrap;
	}

	.empty-state {
		padding: 20px 12px;
		text-align: center;
		font-size: 12px;
		color: var(--color-text-tertiary);
	}

	/* Pack section headers */
	.pack-section {
		border-bottom: 1px solid var(--color-border);
	}

	.pack-section:last-child {
		border-bottom: none;
	}

	:global(.dark) .pack-section {
		border-color: #1e293b;
	}

	.section-header {
		display: flex;
		width: 100%;
		align-items: center;
		gap: 6px;
		padding: 8px 12px;
		border: none;
		background: transparent;
		cursor: pointer;
		font-family: inherit;
		transition: background 0.15s ease;
		border-left: 2.5px solid var(--pack-color, var(--color-border));
		box-sizing: border-box;
	}

	.section-header:hover {
		background: var(--color-surface-secondary);
	}

	:global(.dark) .section-header:hover {
		background: #1a2235;
	}

	.chevron {
		width: 12px;
		height: 12px;
		color: var(--color-text-tertiary);
		flex-shrink: 0;
		transition: transform 0.2s ease;
	}

	.chevron.rotated {
		transform: rotate(180deg);
	}

	:global(.dark) .chevron {
		color: #64748b;
	}

	.section-label {
		font-size: 11px;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.05em;
		color: var(--color-text-secondary);
		flex: 1;
		text-align: left;
	}

	:global(.dark) .section-label {
		color: #94a3b8;
	}

	.section-count {
		font-size: 10px;
		font-weight: 500;
		color: var(--color-text-tertiary);
		background: var(--color-surface-secondary);
		border-radius: 10px;
		padding: 1px 6px;
	}

	:global(.dark) .section-count {
		color: #64748b;
		background: #1e293b;
	}

	/* Footer */
	.palette-footer {
		padding: 8px;
		border-top: 1px solid var(--color-border);
		flex-shrink: 0;
	}

	:global(.dark) .palette-footer {
		border-color: #1e293b;
	}

	.custom-btn {
		display: flex;
		width: 100%;
		align-items: center;
		gap: 10px;
		padding: 7px 10px;
		border: none;
		background: transparent;
		border-radius: 8px;
		cursor: pointer;
		font-family: inherit;
		transition: all 0.15s ease;
	}

	.custom-btn:hover {
		background: var(--color-accent-subtle);
	}

	.custom-btn:hover .item-label {
		color: var(--color-accent);
	}

	:global(.dark) .custom-btn:hover {
		background: rgba(129, 140, 248, 0.08);
	}

	:global(.dark) .custom-btn:hover .item-label {
		color: #818cf8;
	}

	.custom-icon {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 30px;
		height: 30px;
		border-radius: 7px;
		border: 1.5px dashed var(--color-border);
		color: var(--color-text-tertiary);
		flex-shrink: 0;
	}

	:global(.dark) .custom-icon {
		border-color: #334155;
		color: #64748b;
	}

	.custom-input {
		width: 100%;
		padding: 8px 12px;
		font-size: 12px;
		font-family: inherit;
		color: var(--color-text-primary);
		background: var(--color-surface);
		border: 1.5px solid var(--color-accent);
		border-radius: 8px;
		outline: none;
		box-shadow: 0 0 0 2px rgba(99, 102, 241, 0.12);
		box-sizing: border-box;
	}

	:global(.dark) .custom-input {
		background: #1e293b;
		border-color: #818cf8;
		color: #e2e8f0;
		box-shadow: 0 0 0 2px rgba(129, 140, 248, 0.15);
	}

	.custom-hint {
		margin: 6px 0 0;
		text-align: center;
		font-size: 10px;
		color: var(--color-text-tertiary);
	}
</style>

// calm-plugins/vscode/src/webview/panels/NodePalette.tsx
import React, { useState, useMemo } from 'react';
import { initAllPacks, getAllPacks, type PackDefinition, type NodeTypeEntry } from '../../extensions/index.js';

initAllPacks();

interface BuildingBlock {
    id: string;
    name: string;
    behaviour: string;
    nodeType: string;
    category?: string;
    description?: string;
}

interface NodePaletteProps {
    buildingBlocks: BuildingBlock[];
}

export function NodePalette({ buildingBlocks }: NodePaletteProps) {
    const [searchQuery, setSearchQuery] = useState('');
    const [collapsed, setCollapsed] = useState<Record<string, boolean>>({ containers: true, infra: true, standards: true, guidelines: true });

    const packs = useMemo(() => {
        const allPacks = getAllPacks().filter((p: PackDefinition) => p.id !== 'internal');
        const enabled = (window as any).__CALM_ENABLED_PACKS__ as string[] | undefined;
        const excludeNodes = (window as any).__CALM_EXCLUDE_NODES__ as string[] | undefined;
        const excludeSet = new Set(excludeNodes ?? []);
        let filtered = enabled && enabled.length > 0
            ? allPacks.filter((p) => enabled.includes(p.id))
            : allPacks;
        if (excludeSet.size > 0) {
            filtered = filtered.map((p) => ({
                ...p,
                nodes: p.nodes.filter((n) => !excludeSet.has(n.typeId)),
            })).filter((p) => p.nodes.length > 0);
        }
        return filtered;
    }, []);

    const lowerQuery = searchQuery.toLowerCase().trim();
    const isSearching = lowerQuery.length > 0;

    const infraNodes = useMemo(() => buildingBlocks.filter((n) => n.behaviour === 'create-node'), [buildingBlocks]);
    const standardNodes = useMemo(() => buildingBlocks.filter((n) => n.behaviour === 'apply-controls-on-drop' && n.id.startsWith('standards:')), [buildingBlocks]);
    const guidelineNodes = useMemo(() => buildingBlocks.filter((n) => n.behaviour === 'apply-controls-on-drop' && n.id.startsWith('guidelines:')), [buildingBlocks]);

    function matchesSearch(name: string, description?: string): boolean {
        if (!isSearching) return true;
        return name.toLowerCase().includes(lowerQuery) || (description?.toLowerCase().includes(lowerQuery) ?? false);
    }

    function groupByCategory(items: BuildingBlock[]): Array<{ name: string; items: BuildingBlock[] }> {
        const map = new Map<string, BuildingBlock[]>();
        for (const item of items) {
            const cat = item.category ?? 'General';
            if (!map.has(cat)) map.set(cat, []);
            map.get(cat)!.push(item);
        }
        return [...map.entries()].map(([name, items]) => ({ name, items })).sort((a, b) => a.name.localeCompare(b.name));
    }

    const filteredInfra = useMemo(() =>
        groupByCategory(infraNodes).map((g) => ({ ...g, items: g.items.filter((n) => matchesSearch(n.name, n.description)) })).filter((g) => g.items.length > 0),
        [infraNodes, lowerQuery] // eslint-disable-line
    );

    const filteredStandards = useMemo(() =>
        groupByCategory(standardNodes).map((g) => ({ ...g, items: g.items.filter((n) => matchesSearch(n.name, n.description)) })).filter((g) => g.items.length > 0),
        [standardNodes, lowerQuery] // eslint-disable-line
    );

    const filteredGuidelines = useMemo(() =>
        groupByCategory(guidelineNodes).map((g) => ({ ...g, items: g.items.filter((n) => matchesSearch(n.name, n.description)) })).filter((g) => g.items.length > 0),
        [guidelineNodes, lowerQuery] // eslint-disable-line
    );

    const filteredPacks = useMemo(() =>
        packs.map((p: PackDefinition) => ({
            ...p,
            nodes: p.nodes.filter((n: NodeTypeEntry) => matchesSearch(n.label, n.description)),
        })).filter((p: PackDefinition) => p.nodes.length > 0),
        [packs, lowerQuery] // eslint-disable-line
    );

    const toggleSection = (key: string) => setCollapsed((c) => ({ ...c, [key]: !c[key] }));

    const onDragStart = (e: React.DragEvent, node: BuildingBlock) => {
        e.dataTransfer.setData('application/building-block-id', node.id);
        e.dataTransfer.setData('application/building-block-behaviour', node.behaviour);
        e.dataTransfer.setData('application/calm-node-type', node.nodeType);
        e.dataTransfer.setData('application/calm-node-label', node.name);
        e.dataTransfer.effectAllowed = 'move';
    };

    const showContainers = !isSearching || 'container'.includes(lowerQuery);

    return (
        <aside style={paletteStyle}>
            <div style={headerStyle}>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="3" y="3" width="7" height="7" /><rect x="14" y="3" width="7" height="7" />
                    <rect x="3" y="14" width="7" height="7" /><rect x="14" y="14" width="7" height="7" />
                </svg>
                <span>COMPONENTS</span>
            </div>

            <div style={{ position: 'relative', padding: '0 8px 8px' }}>
                <input
                    type="text"
                    placeholder="Search components..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    style={searchInputStyle}
                />
                {searchQuery && (
                    <button onClick={() => setSearchQuery('')} style={clearBtnStyle}>&times;</button>
                )}
            </div>

            {/* Containers */}
            {showContainers && (
                <Section title="CONTAINERS" collapsed={!isSearching && collapsed.containers} onToggle={() => toggleSection('containers')}>
                    <PaletteItem
                        icon="⬚"
                        label="Container"
                        onDragStart={(e) => {
                            e.dataTransfer.setData('application/calm-node-type', 'system');
                            e.dataTransfer.setData('application/calm-node-label', 'Container');
                            e.dataTransfer.setData('application/calm-container', 'true');
                            e.dataTransfer.effectAllowed = 'move';
                        }}
                        title="Create a container to group nodes"
                    />
                </Section>
            )}

            {/* Infrastructure Nodes */}
            {filteredInfra.length > 0 && (
                <Section title={`NODES (${infraNodes.length})`} collapsed={!isSearching && collapsed.infra} onToggle={() => toggleSection('infra')} badge="WS">
                    {filteredInfra.map((group) => (
                        <React.Fragment key={group.name}>
                            {filteredInfra.length > 1 && <div style={subgroupStyle}>{group.name} ({group.items.length})</div>}
                            {group.items.map((node) => (
                                <PaletteItem key={node.id} icon="⬡" label={node.name} onDragStart={(e) => onDragStart(e, node)} title={node.description} />
                            ))}
                        </React.Fragment>
                    ))}
                </Section>
            )}

            {/* Standards */}
            {filteredStandards.length > 0 && (
                <Section title={`STANDARDS (${standardNodes.length})`} collapsed={!isSearching && collapsed.standards} onToggle={() => toggleSection('standards')} badge="WS">
                    {filteredStandards.map((group) => (
                        <React.Fragment key={group.name}>
                            <div style={subgroupStyle}>{group.name} ({group.items.length})</div>
                            {group.items.map((node) => (
                                <PaletteItem key={node.id} icon="📄" label={node.name} onDragStart={(e) => onDragStart(e, node)} title={node.description} />
                            ))}
                        </React.Fragment>
                    ))}
                </Section>
            )}

            {/* Guidelines */}
            {filteredGuidelines.length > 0 && (
                <Section title={`GUIDELINES (${guidelineNodes.length})`} collapsed={!isSearching && collapsed.guidelines} onToggle={() => toggleSection('guidelines')} badge="WS">
                    {filteredGuidelines.map((group) => (
                        <React.Fragment key={group.name}>
                            <div style={subgroupStyle}>{group.name} ({group.items.length})</div>
                            {group.items.map((node) => (
                                <PaletteItem key={node.id} icon="📖" label={node.name} onDragStart={(e) => onDragStart(e, node)} title={node.description} />
                            ))}
                        </React.Fragment>
                    ))}
                </Section>
            )}

            {/* Extension Packs */}
            {filteredPacks.map((pack) => (
                <Section
                    key={pack.id}
                    title={`${pack.label.toUpperCase()} (${pack.nodes.length})`}
                    collapsed={!isSearching && (collapsed[`pack:${pack.id}`] ?? true)}
                    onToggle={() => toggleSection(`pack:${pack.id}`)}
                    borderColor={pack.color.border}
                >
                    {pack.nodes.map((node) => (
                        <PaletteItem
                            key={node.typeId}
                            icon=""
                            iconHtml={node.icon}
                            label={node.label}
                            onDragStart={(e) => {
                                e.dataTransfer.setData('application/calm-node-type', node.typeId);
                                e.dataTransfer.setData('application/calm-node-label', node.label);
                                e.dataTransfer.effectAllowed = 'move';
                            }}
                            title={node.description}
                        />
                    ))}
                </Section>
            ))}

            {/* Empty state */}
            {buildingBlocks.length === 0 && filteredPacks.length === 0 && !isSearching && (
                <div style={{ padding: '12px', fontSize: '11px', color: 'var(--calm-fg-muted)', lineHeight: 1.4 }}>
                    No components found. Ensure your workspace contains a <code style={{ background: 'var(--calm-bg-input)', padding: '1px 4px', borderRadius: '3px', fontSize: '10px' }}>building-blocks/</code> folder with <code style={{ background: 'var(--calm-bg-input)', padding: '1px 4px', borderRadius: '3px', fontSize: '10px' }}>.calm.json</code> files.
                </div>
            )}
        </aside>
    );
}

function Section({ title, collapsed, onToggle, badge, borderColor, children }: { title: string; collapsed: boolean; onToggle: () => void; badge?: string; borderColor?: string; children: React.ReactNode }) {
    const sectionStyle: React.CSSProperties = {
        marginBottom: '4px',
        ...(badge ? { borderLeft: '2px solid #2e7d32', marginLeft: '4px', background: 'rgba(46,125,50,0.04)' } : {}),
        ...(borderColor && !badge ? { borderLeft: `2px solid ${borderColor}`, marginLeft: '4px' } : {}),
    };
    return (
        <div style={sectionStyle}>
            <button onClick={onToggle} style={groupNameStyle}>
                <span style={{ fontSize: '10px', display: 'inline-block', transition: 'transform 0.15s', transform: collapsed ? 'rotate(-90deg)' : 'none' }}>▾</span>
                {badge && <span style={wsBadgeStyle}>{badge}</span>}
                {borderColor && !badge && <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: borderColor, flexShrink: 0 }} />}
                {title}
            </button>
            {!collapsed && children}
        </div>
    );
}

function PaletteItem({ icon, iconHtml, label, onDragStart, title }: { icon?: string; iconHtml?: string; label: string; onDragStart: (e: React.DragEvent) => void; title?: string }) {
    return (
        <div draggable onDragStart={onDragStart} style={itemStyle} title={title}>
            <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '18px', height: '18px', flexShrink: 0 }}>
                {iconHtml ? <span dangerouslySetInnerHTML={{ __html: iconHtml }} /> : <span style={{ fontSize: '14px' }}>{icon}</span>}
            </span>
            <span style={{ fontSize: '12px', fontWeight: 500, color: 'var(--calm-fg)' }}>{label}</span>
        </div>
    );
}

const paletteStyle: React.CSSProperties = { width: '180px', minWidth: '180px', height: '100%', overflowY: 'auto', borderRight: '1px solid var(--calm-border)', background: 'var(--calm-bg)', padding: '8px 0' };
const headerStyle: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: '6px', padding: '4px 12px 6px', fontSize: '11px', fontWeight: 700, letterSpacing: '0.5px', color: 'var(--calm-fg)' };
const searchInputStyle: React.CSSProperties = { width: '100%', height: '28px', padding: '0 24px 0 8px', fontSize: '11px', color: 'var(--calm-fg)', background: 'var(--calm-bg-input)', border: '1px solid var(--calm-border-input)', borderRadius: '4px', outline: 'none' };
const clearBtnStyle: React.CSSProperties = { position: 'absolute', right: '14px', top: '4px', width: '20px', height: '20px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--calm-fg-muted)', fontSize: '14px' };
const groupNameStyle: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: '6px', padding: '4px 12px', fontSize: '10px', fontWeight: 700, letterSpacing: '0.3px', color: 'var(--calm-fg-muted)', background: 'none', border: 'none', width: '100%', cursor: 'pointer', textAlign: 'left' };
const wsBadgeStyle: React.CSSProperties = { fontSize: '8px', fontWeight: 800, padding: '1px 4px', borderRadius: '3px', background: '#2e7d32', color: '#fff', letterSpacing: '0.5px' };
const subgroupStyle: React.CSSProperties = { padding: '3px 12px 3px 20px', fontSize: '9px', fontWeight: 600, color: 'var(--calm-fg-muted)', textTransform: 'capitalize' };
const itemStyle: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: '8px', padding: '6px 12px', cursor: 'grab', borderRadius: '4px', margin: '1px 6px' };
