// calm-plugins/vscode/src/webview/canvas/nodes/GenericNode.tsx
import React from 'react';
import { Handle, Position, NodeResizer, type NodeProps } from 'reactflow';
import { isBuildingBlock, getNodeStyleOverride, CUSTOM_TEXT, CUSTOM_BG, CUSTOM_BORDER } from '../../utils/building-block-style';
import { ValidationBadge } from './ValidationBadge';

export function GenericNode({ id, data, selected }: NodeProps) {
    const isBlock = isBuildingBlock(data as Record<string, unknown>);
    const override = getNodeStyleOverride(data as Record<string, unknown>);
    const errorCount = (data as any).validationErrors ?? 0;
    const warnCount = (data as any).validationWarnings ?? 0;

    return (
        <>
            <Handle type="target" position={Position.Top} style={handleStyle} />
            <Handle type="source" position={Position.Bottom} style={handleStyle} />
            <Handle type="target" position={Position.Left} id="left-target" style={handleStyle} />
            <Handle type="source" position={Position.Right} id="right-source" style={handleStyle} />

            <div style={{
                ...baseStyle,
                ...(isBlock ? buildingBlockStyle : {}),
                ...(selected ? selectedStyle : {}),
                ...(override.background ? { background: override.background } : {}),
            }}>
                <NodeResizer isVisible={selected} minWidth={100} minHeight={40} lineStyle={{ borderColor: '#6366f1' }} handleStyle={{ width: '6px', height: '6px', background: '#6366f1', borderRadius: '2px' }} />
                <ValidationBadge errorCount={errorCount} warnCount={warnCount} nodeId={(data as any).calmId ?? id} />
                <div style={iconStyle}>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={override.text ?? (isBlock ? CUSTOM_TEXT : '#64748b')} strokeWidth="1.5">
                        <rect x="3" y="3" width="18" height="18" rx="3" />
                    </svg>
                </div>
                <span style={{ ...labelStyle, ...(isBlock ? labelBlockStyle : {}), ...(override.text ? { color: override.text } : {}) }}>
                    {(data as any).label ?? (data as any).calmId}
                </span>
            </div>
        </>
    );
}

const baseStyle: React.CSSProperties = {
    position: 'relative', display: 'flex', alignItems: 'center', gap: '7px',
    width: '100%', height: '100%', padding: '8px 10px', boxSizing: 'border-box',
    background: '#f8fafc', border: '1.5px solid #cbd5e1', borderRadius: '10px',
    cursor: 'default', userSelect: 'none',
};
const buildingBlockStyle: React.CSSProperties = {
    background: CUSTOM_BG, borderColor: CUSTOM_BORDER, borderWidth: '2px', borderRadius: '6px',
};
const selectedStyle: React.CSSProperties = {
    borderColor: '#6366f1', boxShadow: '0 0 0 1.5px #6366f1',
};
const iconStyle: React.CSSProperties = { display: 'flex', alignItems: 'center', flexShrink: 0 };
const labelStyle: React.CSSProperties = {
    fontSize: '10px', fontWeight: 600, color: '#1e293b',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
};
const labelBlockStyle: React.CSSProperties = { color: '#ffffff' };
const handleStyle: React.CSSProperties = { width: '8px', height: '8px', background: '#94a3b8', border: '1px solid #64748b' };

// calm-suite/calm-studio/apps/studio/src/lib/canvas/nodes/GenericNode.svelte
<!-- SPDX-FileCopyrightText: 2024 CalmStudio contributors - see NOTICE file -->
<!-- SPDX-License-Identifier: Apache-2.0 -->
<script lang="ts">
	import { Handle, Position, NodeResizer, type NodeProps } from '@xyflow/svelte';
	import ValidationBadge from './ValidationBadge.svelte';
import ThreatBadge from './ThreatBadge.svelte';
	let { id, data, selected }: NodeProps = $props();
	const errorCount = $derived((data as Record<string, unknown>).validationErrors as number ?? 0);
	const warnCount = $derived((data as Record<string, unknown>).validationWarnings as number ?? 0);
	const dataClassification = $derived((data as Record<string, unknown>)['data-classification'] as string | undefined);

	/** Returns badge style for a data-classification value */
	function getClassificationStyle(dc: string): string {
		switch (dc.toLowerCase()) {
			case 'pii': return 'background:#fef2f2;color:#dc2626;border-color:#fca5a5;';
			case 'confidential': return 'background:#fffbeb;color:#d97706;border-color:#fcd34d;';
			case 'public': return 'background:#f0fdf4;color:#16a34a;border-color:#86efac;';
			default: return 'background:#f1f5f9;color:#64748b;border-color:#cbd5e1;';
		}
	}
</script>

<NodeResizer minWidth={80} minHeight={40} isVisible={selected} />
<Handle type="target" position={Position.Top} />
<Handle type="source" position={Position.Bottom} />
<Handle type="target" position={Position.Left} />
<Handle type="source" position={Position.Right} />

{#if data.interfaces}
	{#each data.interfaces as iface, i}
		<Handle type="source" position={Position.Right} id={iface['unique-id']} style="top: {20 + i * 20}%" />
	{/each}
{/if}

<div class="node" class:selected>
	<ValidationBadge {errorCount} {warnCount} nodeId={(data as Record<string, unknown>).calmId as string ?? id} />
<ThreatBadge nodeId={(data as Record<string, unknown>).calmId as string ?? id} />
	<span class="label">{data.label ?? data.calmId}</span>
	{#if data.calmType}
		<span class="badge">{data.calmType}</span>
	{/if}
	{#if dataClassification}
		<span
			class="data-classification-badge"
			style={getClassificationStyle(dataClassification)}
			title="Data classification: {dataClassification}"
		>{dataClassification}</span>
	{/if}
</div>

<style>
	.node {
		position: relative;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		width: 100%;
		height: 100%;
		padding: 8px 10px;
		background: var(--node-generic-bg);
		border: 1.5px dashed var(--node-generic-border);
		border-radius: 4px;
		font-family: var(--node-font);
		cursor: default;
		user-select: none;
	}
	.node.selected {
		border-color: var(--node-selected-ring);
		border-style: solid;
		box-shadow: 0 0 0 1.5px var(--node-selected-ring);
	}
	.label {
		font-size: 10px;
		font-weight: 600;
		color: var(--node-label-color);
		text-align: center;
		max-width: 100px;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.badge {
		font-size: 9px;
		font-weight: 500;
		color: var(--node-generic-badge);
		font-style: italic;
		margin-top: 2px;
	}

	.data-classification-badge {
		font-size: 8px;
		font-weight: 700;
		padding: 1px 5px;
		border-radius: 6px;
		border: 1px solid;
		letter-spacing: 0.04em;
		text-transform: uppercase;
		white-space: nowrap;
		line-height: 1.4;
		margin-top: 2px;
	}
</style>
