// calm-plugins/vscode/src/webview/canvas/nodes/ActorNode.tsx
import React from 'react';
import { Handle, Position, type NodeProps } from 'reactflow';
import { getNodeStyleOverride } from '../../utils/building-block-style';
import { ValidationBadge } from './ValidationBadge';

export function ActorNode({ id, data, selected }: NodeProps) {
    const override = getNodeStyleOverride(data as Record<string, unknown>);
    const fill = override.background ?? '#f5f5f5';
    const errorCount = (data as any).validationErrors ?? 0;
    const warnCount = (data as any).validationWarnings ?? 0;

    return (
        <>
            <Handle type="target" position={Position.Top} style={handleStyle} />
            <Handle type="source" position={Position.Bottom} style={handleStyle} />
            <Handle type="target" position={Position.Left} id="left-target" style={handleStyle} />
            <Handle type="source" position={Position.Right} id="right-source" style={handleStyle} />

            <div style={{ ...nodeStyle, ...(selected ? selectedStyle : {}) }}>
                <ValidationBadge errorCount={errorCount} warnCount={warnCount} nodeId={(data as any).calmId ?? id} />
                <svg width="32" height="40" viewBox="0 0 32 40" fill="none" aria-hidden="true">
                    <circle cx="16" cy="9" r="7" fill={fill} stroke={selected ? '#6366f1' : '#333333'} strokeWidth={selected ? '2' : '1.5'} />
                    <path d="M6 36 Q6 22 16 22 Q26 22 26 36" fill={fill} stroke={selected ? '#6366f1' : '#333333'} strokeWidth={selected ? '2' : '1.5'} />
                </svg>
                <span style={{ ...labelStyle, ...(override.text ? { color: override.text } : {}) }}>{(data as any).label ?? (data as any).calmId}</span>
            </div>
        </>
    );
}

const nodeStyle: React.CSSProperties = {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '3px',
    padding: '4px 6px',
    cursor: 'default',
    userSelect: 'none',
};

const selectedStyle: React.CSSProperties = {};

const labelStyle: React.CSSProperties = {
    fontSize: '10px',
    fontWeight: 600,
    color: 'var(--calm-fg)',
    textAlign: 'center',
    maxWidth: '80px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
};

const handleStyle: React.CSSProperties = { width: '8px', height: '8px', background: '#94a3b8', border: '1px solid #64748b' };

// calm-studio/apps/studio/src/lib/canvas/nodes/ActorNode.svelte
<!-- SPDX-FileCopyrightText: 2024 CalmStudio contributors - see NOTICE file -->
<!-- SPDX-License-Identifier: Apache-2.0 -->
<script lang="ts">
	import { Handle, Position, type NodeProps } from '@xyflow/svelte';
	import ValidationBadge from './ValidationBadge.svelte';
	let { id, data, selected }: NodeProps = $props();
	const errorCount = $derived((data as Record<string, unknown>).validationErrors as number ?? 0);
	const warnCount = $derived((data as Record<string, unknown>).validationWarnings as number ?? 0);
</script>

<Handle type="target" position={Position.Top} />
<Handle type="source" position={Position.Bottom} />
<Handle type="target" position={Position.Left} />
<Handle type="source" position={Position.Right} />

{#if data.interfaces}
	{#each data.interfaces as iface, i}
		<Handle type="source" position={Position.Right} id={iface['unique-id']} style="top: {20 + i * 20}%" />
	{/each}
{/if}

<div class="node" class:selected>
	<ValidationBadge {errorCount} {warnCount} nodeId={(data as Record<string, unknown>).calmId as string ?? id} />
	<svg width="32" height="40" viewBox="0 0 32 40" fill="none" aria-hidden="true">
		<circle cx="16" cy="9" r="7" fill="var(--node-actor-bg)" stroke="var(--node-actor-stroke)" stroke-width="1.5" />
		<path d="M6 36 Q6 22 16 22 Q26 22 26 36" fill="var(--node-actor-bg)" stroke="var(--node-actor-stroke)" stroke-width="1.5" />
	</svg>
	<span class="label">{data.label ?? data.calmId}</span>
</div>

<style>
	.node {
		position: relative;
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 3px;
		padding: 4px 6px;
		cursor: default;
		user-select: none;
		font-family: var(--node-font);
	}
	.node.selected svg circle,
	.node.selected svg path {
		stroke: var(--node-selected-ring);
		stroke-width: 2;
	}
	.label {
		font-size: 10px;
		font-weight: 600;
		color: var(--node-label-color);
		text-align: center;
		max-width: 80px;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
</style>
